[package]
name = "zero_first_crate"
version = "0.1.0"
edition = "2021"
description = "test publish a crate for the first time"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
